# Generated by Django 3.1.6 on 2021-04-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaccount',
            name='line_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
