# Generated by Django 3.1.6 on 2021-05-16 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myNote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycodes',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myNote.programminglanguage'),
        ),
    ]
